


#https://blog.sebastian-daschner.com/entries/init-databases-quarkus
#%dev.quarkus.hibernate-orm.database.generation=drop-and-create
#%dev.quarkus.hibernate-orm.sql-load-script=scripts/load-data.sql

#quarkus.hibernate-orm.database.generation=drop-and-create
#quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/postgres
#quarkus.datasource.jdbc.username=postgres
#quarkus.datasource.jdbc.password=postgres
#quarkus.datasource.jdbc.db-kind=postgresql

quarkus.http.cors=true
quarkus.http.cors.origins=http://localhost:3001,https://food.sondreandersen.dev,https://keycloak.sondreandersen.dev

%prod.quarkus.flyway.enabled=true
%prod.quarkus.flyway.migrate-at-start=true
quarkus.flyway.enabled=false
quarkus.flyway.migrate-at-start=false

%dev.quarkus.http.port=8080

quarkus.oidc.auth-server-url=https://keycloak.sondreandersen.dev/realms/data-driven-dinner
#quarkus.oidc.authentication.verify-access-token=true
#quarkus.oidc.credentials.client-secret.value=123
quarkus.oidc.client-id=recipe-service
#quarkus.oidc.token-state-manager.encryption-secret=91DF8946-E95F-45DE-A9EA-527221F21218 should be read from secret manager

# Usikker på om dette er redirect for å gi token tilbake, eller redicret for at backend skal ta vare på token
#quarkus.oidc.authentication.redirect-path=/oauth2-callback
# Quarkus is running behind Traefik reverse proxy that terminates TLS... so to make it understand that is should redirect to https
quarkus.http.proxy.enable-forwarded-host=true

#quarkus.http.proxy.proxy-address-forwarding=true
quarkus.oidc.authentication.pkce-required=true

quarkus.oidc.application-type=service
#quarkus.oidc.application-type=hybrid
# https://quarkus.io/guides/security-oidc-code-flow-authentication#single-page-applications

quarkus.http.auth.permission.secured.paths=/*
quarkus.http.auth.permission.secured.policy=authenticated