


#https://blog.sebastian-daschner.com/entries/init-databases-quarkus
#%dev.quarkus.hibernate-orm.database.generation=drop-and-create
#%dev.quarkus.hibernate-orm.sql-load-script=scripts/load-data.sql

#quarkus.hibernate-orm.database.generation=drop-and-create
#quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/postgres
#quarkus.datasource.jdbc.username=postgres
#quarkus.datasource.jdbc.password=postgres
#quarkus.datasource.jdbc.db-kind=postgresql

quarkus.http.cors=true
quarkus.http.cors.origins=http://localhost:3001,https://food.sondreandersen.dev

%prod.quarkus.flyway.enabled=true
%prod.quarkus.flyway.migrate-at-start=true
quarkus.flyway.enabled=false
quarkus.flyway.migrate-at-start=false

%dev.quarkus.http.port=8080

quarkus.oidc.auth-server-url=https://keycloak.sondreandersen.dev/realms/data-driven-dinner
#quarkus.oidc.authentication.verify-access-token=true
#quarkus.oidc.credentials.client-secret.value=123
quarkus.oidc.client-id=quarkus-backend-client
#quarkus.oidc.token-state-manager.encryption-secret=91DF8946-E95F-45DE-A9EA-527221F21218 should be read from secret manager

quarkus.oidc.application-type=web-app

quarkus.http.auth.permission.secured.paths=/*
quarkus.http.auth.permission.secured.policy=authenticated